### ISSUE TITLE
frida.ProcessNotFoundError: unable to find process with name 'simple0'

### ISSUE THREAD

**Issue by cxapython** [juliusdeane/beginningfrida#1]
hello,how to get  process with name 'simple0'

**Comment by juliusdeane** [comment]
Hello :)

You should run simple0 before playing with the scripts. Typically I open two terminal (or a Tilix session). The moment a process with name simple0 is running, the python script will attach to it.

See the line:

`session = frida.attach("simple0")`

The attach method will look for a process name "simple0" (you may pass the process PID, too).

To obtain simple0 executable, you should compile it, for example with gcc:

`gcc -o simple0 simple0.c`

Has no additional libraries, nor dependencies, so this quick compile tip should work.

**Comment by juliusdeane** [comment]
Hello :)

You should run simple0 before playing with the scripts. Typically I open two terminal (or a Tilix session). The moment
